// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainService.Core.Data;

#nullable disable

namespace TrainService.Core.Data.Migrations
{
    [DbContext(typeof(TrainDbContext))]
    [Migration("20260507064428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainService.Core.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<string>("DestinationStation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fares")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceStation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TotalSeats")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TrainNumber")
                        .IsUnique();

                    b.HasIndex("SourceStation", "DestinationStation");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TrainService.Core.Models.TrainBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PNR")
                        .HasColumnType("bigint");

                    b.Property<string>("PassengerDetails")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TravelDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PNR")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TrainId", "TravelDate", "Status");

                    b.ToTable("TrainBookings", t =>
                        {
                            t.HasCheckConstraint("CK_TrainBooking_SeatClass", "\"SeatClass\" IN ('Sleeper', '3AC', '2AC', '1AC')");

                            t.HasCheckConstraint("CK_TrainBooking_Status", "\"Status\" IN ('Confirmed', 'Cancelled')");

                            t.HasCheckConstraint("CK_TrainBooking_TotalAmount", "\"TotalAmount\" > 0");
                        });
                });

            modelBuilder.Entity("TrainService.Core.Models.TrainBooking", b =>
                {
                    b.HasOne("TrainService.Core.Models.Train", "Train")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainService.Core.Models.Train", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
